"""
Django settings for orq_descriptivo project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, TimestampType

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wg14fkd7pa7syrrj8zo^si6cljtt1#!+62q*wr=i+ydn9v=oqw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orq_descriptivo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orq_descriptivo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR , 
    BASE_DIR / 'static/json/', 
    BASE_DIR / 'static/logs/', 
    BASE_DIR / 'static/source_data/'
]

# Rutas
crudos=str(BASE_DIR).replace("\\", "/")+"/modules/tablas/crudos/"
datamart=str(BASE_DIR).replace("\\", "/")+"/modules/tablas/datamart/"
planos=str(BASE_DIR).replace("\\", "/")+"/modules/modelos/datos/planos/"
pick=str(BASE_DIR).replace("\\", "/")+"/modules/modelos/datos/pickle/"

# Rutas Completas
archivo_21 = 'anexo_dptal_pobreza_multidimensional_21.xls'
archivo2 = 'anexo_nal_pobreza_multidimensional_21.xls'
ruta_archivo_21 = crudos + archivo_21
ruta_archivo2 = crudos + archivo2
# stoplist=pd.read_csv('datos/planos/Stoplist.csv')

# Hojas de excel
hojas={
    1:"IPM_Departamentos",
    2:"IPM_Regiones",
    3:"IPM_Variables_Departamento ",
    4:"IPM_Variables_Región",
    5:"IPM_Dominios",
    6:"IPM_Variables",
    7:"Contribuciones IA_IPM" 
}


# Datos estaticos
schema_secop = StructType([StructField('UID', StringType(), True), \
                        StructField('Anno Cargue SECOP', IntegerType(), True), \
                        StructField('Anno Firma del Contrato', IntegerType(), True), \
                        StructField('Nivel Entidad', StringType(), True), \
                        StructField('Orden Entidad', StringType(), True), \
                        StructField('Nombre de la Entidad', StringType(), True), \
                        StructField('NIT de la Entidad', StringType(), True), \
                        StructField('Código de la Entidad', StringType(), True), \
                        StructField('ID Tipo de Proceso', StringType(), True), \
                        StructField('Tipo de Proceso', StringType(), True), \
                        StructField('Estado del Proceso', StringType(), True), \
                        StructField('Causal de Otras Formas de Contratacion Directa', StringType(), True), \
                        StructField('ID Regimen de Contratacion', StringType(), True), \
                        StructField('Regimen de Contratacion', StringType(), True), \
                        StructField('ID Objeto a Contratar', StringType(), True), \
                        StructField('Objeto a Contratar', StringType(), True), \
                        StructField('Detalle del Objeto a Contratar', StringType(), True), \
                        StructField('Tipo de Contrato', StringType(), True), \
                        StructField('Municipio Obtencion', StringType(), True), \
                        StructField('Municipio Entrega', StringType(), True), \
                        StructField('Municipios Ejecucion', StringType(), True), \
                        StructField('Fecha de Cargue en el SECOP', TimestampType(), True), \
                        StructField('Numero de Constancia', StringType(), True), \
                        StructField('Numero de Proceso', StringType(), True), \
                        StructField('Numero del Contrato', StringType(), True), \
                        StructField('Cuantia Proceso', StringType(), True), \
                        StructField('ID Grupo', StringType(), True), \
                        StructField('Nombre Grupo', StringType(), True), \
                        StructField('ID Familia', StringType(), True), \
                        StructField('Nombre Familia', StringType(), True), \
                        StructField('ID Clase', StringType(), True), \
                        StructField('Nombre Clase', StringType(), True), \
                        StructField('ID Ajudicacion', StringType(), True), \
                        StructField('Tipo Identifi del Contratista', StringType(), True), \
                        StructField('Identificacion del Contratista', StringType(), True), \
                        StructField('Nom Raz Social Contratista', StringType(), True), \
                        StructField('Dpto y Muni Contratista', StringType(), True), \
                        StructField('Tipo Doc Representante Legal', StringType(), True), \
                        StructField('Identific del Represen Legal', StringType(), True), \
                        StructField('Nombre del Represen Legal', StringType(), True), \
                        StructField('Fecha de Firma del Contrato', TimestampType(), True), \
                        StructField('Fecha Ini Ejec Contrato', TimestampType(), True), \
                        StructField('Plazo de Ejec del Contrato', IntegerType(), True), \
                        StructField('Rango de Ejec del Contrato', StringType(), True), \
                        StructField('Tiempo Adiciones en Dias', IntegerType(), True), \
                        StructField('Tiempo Adiciones en Meses', IntegerType(), True), \
                        StructField('Fecha Fin Ejec Contrato', TimestampType(), True), \
                        StructField('Compromiso Presupuestal', StringType(), True), \
                        StructField('Cuantia Contrato', StringType(), True), \
                        StructField('Valor Total de Adiciones', StringType(), True), \
                        StructField('Valor Contrato con Adiciones', StringType(), True), \
                        StructField('Objeto del Contrato a la Firma', StringType(), True), \
                        StructField('ID Origen de los Recursos', StringType(), True), \
                        StructField('Origen de los Recursos', StringType(), True), \
                        StructField('Codigo BPIN', StringType(), True), \
                        StructField('Proponentes Seleccionados', StringType(), True), \
                        StructField('Calificacion Definitiva', StringType(), True), \
                        StructField('ID Sub Unidad Ejecutora', StringType(), True), \
                        StructField('Nombre Sub Unidad Ejecutora', StringType(), True), \
                        StructField('Ruta Proceso en SECOP I', StringType(), True), \
                        StructField('Moneda', StringType(), True), \
                        StructField('EsPostConflicto', StringType(), True), \
                        StructField('Marcacion Adiciones', StringType(), True), \
                        StructField('Posicion Rubro', StringType(), True), \
                        StructField('Nombre Rubro', StringType(), True), \
                        StructField('Valor Rubro', StringType(), True), \
                        StructField('Sexo RepLegal Entidad', StringType(), True), \
                        StructField('Pilar Acuerdo Paz', StringType(), True), \
                        StructField('Punto Acuerdo Paz', StringType(), True), \
                        StructField('Municipio Entidad', StringType(), True), \
                        StructField('Departamento Entidad', StringType(), True), \
                        StructField('Ultima Actualizacion', TimestampType(), True), \
                        StructField('Fecha Liquidacion', TimestampType(), True)
                        ])

schema_dpto_reg = StructType([ \
    StructField('Dpto_SECOP', StringType(), True), \
    StructField('Dpto_DANE', StringType(), True), \
    StructField('Region_DANE', StringType(), True)
  ])

columnas_drop = ('Nombre de la Entidad', 'NIT de la Entidad', 'Código de la Entidad', 'ID Tipo de Proceso', \
                        'Causal de Otras Formas de Contratacion Directa', 'ID Regimen de Contratacion', 'Regimen de Contratacion',\
                        'ID Objeto a Contratar', 'Municipio Obtencion', 'Municipio Entrega', 'Municipios Ejecucion', \
                        'Fecha de Cargue en el SECOP', 'Numero de Constancia', 'Numero de Proceso', 'Numero del Contrato', \
                        'ID Grupo', 'ID Familia', 'ID Clase', 'ID Ajudicacion', 'Tipo Identifi del Contratista', \
                        'Identificacion del Contratista', 'Nom Raz Social Contratista', 'Dpto y Muni Contratista', \
                        'Tipo Doc Representante Legal', 'Identific del Represen Legal', 'Nombre del Represen Legal', \
                        'Fecha de Firma del Contrato', 'Compromiso Presupuestal', 'Valor Total de Adiciones', \
                        'ID Origen de los Recursos', 'Origen de los Recursos', 'Codigo BPIN', 'Proponentes Seleccionados', \
                        'Calificacion Definitiva', 'ID Sub Unidad Ejecutora', 'Nombre Sub Unidad Ejecutora', \
                        'Ruta Proceso en SECOP I', 'EsPostConflicto', 'Marcacion Adiciones', 'Posicion Rubro', \
                        'Nombre Rubro', 'Valor Rubro', 'Sexo RepLegal Entidad', 'Pilar Acuerdo Paz', 'Punto Acuerdo Paz', \
                        'Municipio Entidad', 'Ultima Actualizacion', 'Fecha Liquidacion')

old_new_names_dict = {'Anno Cargue SECOP': 'Anno_Cargue_SECOP',
                      'Anno Firma del Contrato': 'Anno_Firma_Contrato',
                      'Nivel Entidad': 'Nivel_Entidad',
                      'Orden Entidad': 'Orden_Entidad',
                      'Tipo de Proceso': 'Tipo_Proceso',
                      'Estado del Proceso': 'Estado_Proceso',
                      'Objeto a Contratar': 'Objeto_Contratar',
                      'Detalle del Objeto a Contratar': 'Detalle_Objeto_Contratar',
                      'Tipo de Contrato': 'Tipo_Contrato',
                      'Cuantia Proceso': 'Cuantia_Proceso',
                      'Nombre Grupo': 'Nombre_Grupo',
                      'Nombre Familia': 'Nombre_Familia',
                      'Nombre Clase': 'Nombre_Clase',
                      'Fecha Ini Ejec Contrato': 'Fecha_Ini_Ejec_Contrato',
                      'Plazo de Ejec del Contrato': 'Plazo_Ejec_Contrato',
                      'Rango de Ejec del Contrato': 'Rango_Ejec_Contrato',
                      'Tiempo Adiciones en Dias': 'Tiempo_Adiciones_Dias',
                      'Tiempo Adiciones en Meses': 'Tiempo_Adiciones_Meses',
                      'Fecha Fin Ejec Contrato': 'Fecha_Fin_Ejec_Contrato',
                      'Cuantia Contrato': 'Cuantia_Contrato',
                      'Valor Contrato con Adiciones': 'Valor_Contrato_Total',
                      'Objeto del Contrato a la Firma': 'Objeto_Contrato_firmado',
                      'Origen de los Recursos': 'Origen_Recursos',
                      'Departamento Entidad': 'ID_Departamento'
                      }

cols_integer = ["Anno_Cargue_SECOP", "Anno_Firma_Contrato", "Cuantia_Proceso", "Plazo_Ejec_Contrato", \
               "Tiempo_Adiciones_Dias", "Tiempo_Adiciones_Meses", "Cuantia_Contrato", "Valor_Contrato_Total"]

cols_date = ['Fecha_Ini_Ejec_Contrato', 'Fecha_Fin_Ejec_Contrato']

cols_str = ['UID', 'Nivel_Entidad', 'Orden_Entidad', 'Tipo_Proceso', 'Estado_Proceso', \
            'Objeto_Contratar', 'Detalle_Objeto_Contratar', 'Tipo_Contrato',  \
            'Nombre_Grupo', 'Nombre_Familia', 'Nombre_Clase', 'Rango_Ejec_Contrato', \
            'Objeto_Contrato_firmado', 'Moneda', 'ID_Departamento']

cols_money = ['Cuantia_Proceso', 'Cuantia_Contrato', 'Valor_Contrato_Total']



columnas = [
    list(range(4)),
    [0, 4, 5, 6],
    [0, 7, 8, 9],
    [0, 10, 11, 12]
]

tipos = [
    {'total': 'total', 'cabeceras': 'cabeceras', 'centros_poblados_rural_disperso': 'centros_poblados_rural_disperso'},
    {'total': 'total', 'cabeceras': 'cabeceras', 'centros_poblados_rural_disperso': 'centros_poblados_rural_disperso'},
    {'total': 'total', 'cabeceras': 'cabeceras', 'centros_poblados_rural_disperso': 'centros_poblados_rural_disperso'},
    {'total': 'total', 'cabeceras': 'cabeceras', 'centros_poblados_rural_disperso': 'centros_poblados_rural_disperso'}
]

Area_dicc = {'cabeceras': 'Cabecera',
                 'centros_poblados_rural_disperso': 'Centros Poblados y Rural Disperso',
                 'total': 'Total'}

# Crear diccionario para cambiar los términos del Area_IPM
Area_dicc_zona = {'Cabecera': 'Cabecera',
            'Centros poblados y rural disperso*': 'Centros Poblados y Rural Disperso',
            'Nacional*': 'Total'}

    # Ajustar descripción del Área IPM
Area_dicc1 = {'Cabecera': 'Cabecera',
                 'Centros poblados \ny rural disperso': 'Centros Poblados y Rural Disperso',
                 'Nacional': 'Total'}

Region_dict = {'Caribe': 'Caribe',
                   'Oriental': 'Oriental',
                   'Central': 'Central',
                   'Pacífica (sin incluir Valle del Cauca)': 'Pacífica (sin Valle del Cauca)',
                   'Bogotá': 'Bogotá',
                   'Antioquia': 'Antioquia',
                   'Valle del Cauca': 'Valle del Cauca',
                   'San Andrés': 'San Andrés',
                   'Orinoquía-Amazonía': 'Orinoquía-Amazonía'}

anios = [2018, 2019, 2020, 2021]

#IPM Variables por departamento
year_structure = {
    2018: {'columns': [0, 1, 2, 3, 4], 'nombres': ['departamento', 'variable', 'total', 'cabeceras', 'centros_poblados_rural_disperso'], 'tipo': 'total'},
    2019: {'columns': [0, 1, 5, 6, 7], 'nombres': ['departamento', 'variable', 'total', 'cabeceras', 'centros_poblados_rural_disperso'], 'tipo': 'cabeceras'},
    2020: {'columns': [0, 1, 8, 9, 10], 'nombres': ['departamento', 'variable', 'total', 'cabeceras', 'centros_poblados_rural_disperso'], 'tipo': 'centros_poblados_rural_disperso'},
    2021: {'columns': [0, 1, 11, 12, 13], 'nombres': ['departamento', 'variable', 'total', 'cabeceras', 'centros_poblados_rural_disperso'], 'tipo': 'total'}
}


nuevos_nombres = ['departamento','variable', 'total', 'cabeceras', 'centros_poblados_rural_disperso',
                  'total_1', 'cabeceras_1', 'centros_poblados_rural_disperso_1',
                  'total_2', 'cabeceras_2', 'centros_poblados_rural_disperso_2',
                  'total_3', 'cabeceras_3', 'centros_poblados_rural_disperso_3']
nombre_columna = "departamento"

departamentos = ["antioquia", "atlantico", "bogota", "bolivar", "boyaca", "caldas", "caqueta", "cauca", "cesar",
                     "cordoba", "cundinamarca", "choco", "huila", "la_guajira", "magdalena", "meta", "narino",
                     "norte_de_santander", "quindio", "risarlda", "santander", "sucre", "tolima", "valle_del_cauca",
                     "arauca", "casanare", "putumayo", "san_andres", "amazonas", "guainia", "guaviare", "vaupes",
                     "vichada"]


departamentos_tupla = [
    ("antioquia", 14),
    ("atlantico", 40),
    ("bogota", 66),
    ("bolivar", 92),
    ("boyaca", 118),
    ("caldas", 144),
    ("caqueta", 170),
    ("cauca", 196),
    ("cesar", 222),
    ("cordoba", 248),
    ("cundinamarca", 274),
    ("choco", 300),
    ("huila", 326),
    ("la_guajira", 352),
    ("magdalena", 378),
    ("meta", 404),
    ("narino", 430),
    ("norte_de_santander", 456),
    ("quindio", 482),
    ("risaralda", 508),
    ("santander", 534),
    ("sucre", 560),
    ("tolima", 586),
    ("valle_del_cauca", 612),
    ("arauca", 638),
    ("casanare", 664),
    ("putumayo", 690),
    ("san_andres", 716),
    ("amazonas", 742),
    ("guainia", 768),
    ("guaviare", 794),
    ("vaupes", 820),
    ("vichada", 846)
]

departamentos_tupla1 = [
    ('Antioquia', 13),
    ('Atlántico', 28),
    ('Bogotá', 43),
    ('Bolívar', 58),
    ('Boyacá', 74),
    ('Caldas', 89),
    ('Caquetá', 104),
    ('Cauca', 119),
    ('Cesar', 134),
    ('Córdoba', 149),
    ('Cundinamarca', 164),
    ('Chocó', 179),
    ('Huila', 194),
    ('La Guajira', 209),
    ('Magdalena', 224),
    ('Meta', 239),
    ('Nariño', 254),
    ('Norte de Santander', 269),
    ('Quindío', 284),
    ('Risaralda', 299),
    ('Santander', 314),
    ('Sucre', 329),
    ('Tolima', 344),
    ('Valle del Cauca', 360),
    ('Arauca', 375),
    ('Casanare', 390),
    ('Putumayo', 405),
    ('San Andrés', 420),
    ('Amazonas', 435),
    ('Guainía', 450),
    ('Guaviare', 465),
    ('Vaupés', 480),
    ('Vichada', 495)
]

# Crear diccionario para cambiar los términos de la región
region_dict = {'Caribe': 'Caribe',
                'Oriental': 'Oriental',
                'Central': 'Central',
                'Pacífica (sin incluir Valle del Cauca)': 'Pacífica (sin Valle del Cauca)',
                'Bogotá': 'Bogotá',
                'Antioquia': 'Antioquia',
                'Valle del Cauca': 'Valle del Cauca',
                'San Andrés': 'San Andrés',
                'Orinoquía-Amazonía': 'Orinoquía-Amazonía'}


skiprows_dict = {
    'Caribe': range(13),
    'Oriental': range(38),
    'Central': range(63),
    'Pacífica': range(88),
    'Bogotá': range(113),
    'Antioquia': range(138),
    'Valle del Cauca': range(163),
    'San Andrés': range(189),
    'Orinoquía-Amazonía': range(214)
}

nrows_dict = {
    'Caribe': 15,
    'Oriental': 15,
    'Central': 15,
    'Pacífica': 15,
    'Bogotá': 15,
    'Antioquia': 15,
    'Valle del Cauca': 15,
    'San Andrés': 15,
    'Orinoquía-Amazonía': 15
}

# Definir los saltos de filas por área
skiprows_dict1 = {
    'Total': range(14),
    'Cabecera': range(40),
    'Centros Poblados y Rural Disperso': range(66)
}

# Definir los saltos de filas por año
skiprows_dict2 = {
    2021: range(14),
    2020: range(45),
    2019: range(76),
    2018: range(107),
    2016: range(155),
    2015: range(187),
    2014: range(218),
    2013: range(250),
    2012: range(282),
    2011: range(314),
    2010: range(346)
}

# Definir los años
anios2 = [2021, 2020, 2019, 2018, 2016, 2015, 2014, 2013, 2012, 2011, 2010]

# Definir los saltos de filas por año
skiprows_dict3 = {
    2021: range(30),
    2020: range(61),
    2019: range(92),
    2018: range(123),
    2016: range(171),
    2015: range(203),
    2014: range(235),
    2013: range(267),
    2012: range(299),
    2011: range(331),
    2010: range(363)
}




stopwords_analisis = ['municipio', 'municipal', 'departamento', 'san', 'jose',  'urbano','rural', 'realizar','vereda',
                      'veredar', 'calle', 'carrera', 'sector','santa', 'corregimiento', 'norte', 'esfuerzo', 'aunar',
                      'locativa', 'sur', 'oriente', 'occidente', 'segun', 'jurisdiccion', 'barrio', 'etapa', 'casco',
                      'contrato', 'contratar', 'realizar', 'convenio', 'marco', 'plan', 'apoyo', 'ubicado', 'area',
                      'centro', 'sector', 'mediante', 'sitio', 'area', 'sede','calles', 'carreras','adecuacion','cra']


lista_departamento = ['amazonas',  'andres', 'antioquia', 'arauca', 'atlantico', 'bogotá', 'bolivar', 'boyaca', 'caldas',
                      'caqueta', 'caquetá', 'casanare', 'cauca', 'cesar', 'choco', 'cordoba', 'cundinamarca', 'guainia',
                      'guajira', 'guaviare', 'huila', 'la_guajira', 'magdalena', 'meta', 'narino', 'nariño',
                      'norte_de_santander', 'providenciacatalina', 'putumayo', 'quindio', 'risaralda',
                      'san_andres_y_providencia', 'santander', 'sucre', 'tolima', 'valle', 'valle_del_cauca', 'vaupes','vichada']